cc_test(
    name = "test_common",
    srcs = [
        "test_common.cpp",
    ],
    deps = [
        "//cpp/lib:common",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "test_sorting",
    srcs = [
        "test_sorting.cpp",
    ],
    deps = [
        "//cpp/lib:common",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
    visibility = ["//visibility:public"],
)