cc_binary(
    name = "main",
    srcs = ["main.cpp"],
    deps = [],
)

cc_binary(
    name = "example_unique_ptr",
    srcs = ["example_unique_ptr.cpp"],
    deps = [],
)

cc_binary(
    name = "example_shared_ptr",
    srcs = ["example_shared_ptr.cpp"],
    deps = [],
)